<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataSeeder extends Seeder
{
    public function run()
    {
        // Candidate Profiles
        \DB::table('candidate_profile')->insert([
            [
                'user_id' => 2,
                'first_name' => 'Pol',
                'last_name' => 'García Martínez',
                'phone' => '612345678',
                'city' => 'Barcelona',
                'photo_url' => null,
                'disability_type_id' => 1,
                'disability_degree' => 45,
                'accessibility_needs' => 'Rampa de acceso y ascensor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'first_name' => 'Roger',
                'last_name' => 'Malgrat González',
                'phone' => '623456789',
                'city' => 'Barcelona',
                'photo_url' => null,
                'disability_type_id' => 2,
                'disability_degree' => 65,
                'accessibility_needs' => 'Lector de pantalla y documentos en formato accesible',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'first_name' => 'Arnau',
                'last_name' => 'Vidal López',
                'phone' => '634567890',
                'city' => 'Madrid',
                'photo_url' => null,
                'disability_type_id' => 3,
                'disability_degree' => 33,
                'accessibility_needs' => 'Comunicación escrita preferente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'first_name' => 'Pau',
                'last_name' => 'Ferrer Soler',
                'phone' => '645678901',
                'city' => 'Valencia',
                'photo_url' => null,
                'disability_type_id' => null,
                'disability_degree' => null,
                'accessibility_needs' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Company Profiles
        \DB::table('company_profile')->insert([
            [
                'user_id' => 6,
                'company_name' => 'Mercadona S.A.',
                'description' => 'Cadena de supermercados líder en España con más de 1.600 tiendas. Comprometidos con la inclusión laboral y la igualdad de oportunidades.',
                'sector' => 'Distribución y Alimentación',
                'city' => 'Valencia',
                'contact_phone' => '963883333',
                'website' => 'https://www.mercadona.es',
                'logo_url' => null,
                'offers_adapted_positions' => true,
                'offers_remote_work' => false,
                'offers_reasonable_adjustments' => true,
                'validation_status' => 'VALIDATED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'company_name' => 'Inditex S.A.',
                'description' => 'Grupo textil multinacional español. Incluye marcas como Zara, Pull&Bear, Massimo Dutti y Bershka.',
                'sector' => 'Moda y Retail',
                'city' => 'A Coruña',
                'contact_phone' => '981185400',
                'website' => 'https://www.inditex.com',
                'logo_url' => null,
                'offers_adapted_positions' => true,
                'offers_remote_work' => true,
                'offers_reasonable_adjustments' => true,
                'validation_status' => 'VALIDATED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'company_name' => 'Telefónica S.A.',
                'description' => 'Compañía de telecomunicaciones líder en España y Latinoamérica. Innovación, tecnología y compromiso con la diversidad.',
                'sector' => 'Telecomunicaciones',
                'city' => 'Madrid',
                'contact_phone' => '900111004',
                'website' => 'https://www.telefonica.com',
                'logo_url' => null,
                'offers_adapted_positions' => true,
                'offers_remote_work' => true,
                'offers_reasonable_adjustments' => true,
                'validation_status' => 'VALIDATED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Job Offers
        \DB::table('job_offer')->insert([
            [
                'company_user_id' => 6,
                'category_id' => 4,
                'contract_type_id' => 1,
                'workday_type_id' => 1,
                'modality_id' => 1,
                'title' => 'Reponedor/a de supermercado',
                'description' => 'Buscamos personas responsables para la reposición de productos en nuestras tiendas. Se ofrece formación inicial y contrato estable.',
                'requirements' => 'Capacidad para trabajar en equipo. Disponibilidad horaria.',
                'adaptations' => 'Puesto adaptado para personas con movilidad reducida.',
                'city' => 'Barcelona',
                'is_adapted' => true,
                'status' => 'PUBLISHED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_user_id' => 6,
                'category_id' => 2,
                'contract_type_id' => 1,
                'workday_type_id' => 2,
                'modality_id' => 1,
                'title' => 'Auxiliar administrativo/a',
                'description' => 'Incorporación al departamento de administración para gestión documental, atención telefónica y tareas de apoyo.',
                'requirements' => 'Ciclo Formativo en Administración. Conocimientos de Excel y SAP valorables.',
                'adaptations' => 'Puesto de trabajo con escritorio regulable en altura.',
                'city' => 'Valencia',
                'is_adapted' => true,
                'status' => 'PUBLISHED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_user_id' => 7,
                'category_id' => 3,
                'contract_type_id' => 2,
                'workday_type_id' => 1,
                'modality_id' => 1,
                'title' => 'Dependiente/a Zara',
                'description' => 'Atención al cliente, organización del punto de venta y gestión del stock en tienda Zara.',
                'requirements' => 'Experiencia en atención al cliente. Don de gentes y orientación al cliente.',
                'adaptations' => null,
                'city' => 'Madrid',
                'is_adapted' => false,
                'status' => 'PUBLISHED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_user_id' => 7,
                'category_id' => 7,
                'contract_type_id' => 1,
                'workday_type_id' => 1,
                'modality_id' => 3,
                'title' => 'Especialista en Marketing Digital',
                'description' => 'Gestión de campañas digitales, análisis de métricas y estrategia de contenidos para las marcas del grupo.',
                'requirements' => 'Grado en Marketing o similar. 2 años de experiencia en marketing digital. Google Ads y Meta Ads.',
                'adaptations' => 'Opción de teletrabajo 3 días a la semana.',
                'city' => 'Barcelona',
                'is_adapted' => true,
                'status' => 'PUBLISHED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_user_id' => 8,
                'category_id' => 1,
                'contract_type_id' => 1,
                'workday_type_id' => 1,
                'modality_id' => 2,
                'title' => 'Desarrollador/a Full Stack',
                'description' => 'Desarrollo de aplicaciones web con Laravel y Vue.js. Participación en proyectos de transformación digital.',
                'requirements' => 'Grado en Ingeniería Informática. Experiencia con PHP, Laravel, Vue.js. Conocimiento de bases de datos MySQL.',
                'adaptations' => '100% remoto. Herramientas accesibles proporcionadas.',
                'city' => 'Madrid',
                'is_adapted' => true,
                'status' => 'PUBLISHED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_user_id' => 8,
                'category_id' => 1,
                'contract_type_id' => 3,
                'workday_type_id' => 2,
                'modality_id' => 3,
                'title' => 'Becario/a Ciberseguridad',
                'description' => 'Prácticas en el equipo de ciberseguridad. Apoyo en auditorías, monitorización de amenazas y documentación.',
                'requirements' => 'Estudiante de últimos cursos de Informática o Telecomunicaciones. Interés en ciberseguridad.',
                'adaptations' => 'Horario flexible.',
                'city' => 'Barcelona',
                'is_adapted' => false,
                'status' => 'PUBLISHED',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Applications
        \DB::table('application')->insert([
            [
                'offer_id' => 1,
                'candidate_user_id' => 2,
                'status' => 'SENT',
                'company_notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'offer_id' => 5,
                'candidate_user_id' => 3,
                'status' => 'IN_REVIEW',
                'company_notes' => 'Perfil interesante, citar para entrevista.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'offer_id' => 4,
                'candidate_user_id' => 4,
                'status' => 'ACCEPTED',
                'company_notes' => 'Incorporación prevista para el 15 de marzo.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'offer_id' => 6,
                'candidate_user_id' => 5,
                'status' => 'SENT',
                'company_notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'offer_id' => 5,
                'candidate_user_id' => 2,
                'status' => 'SENT',
                'company_notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
